id: Cortex XDR Blueprint
inputs: []
name: Cortex XDR Blueprint
fromversion: 5.0.0
outputs: []
starttaskid: "0"
description: Compares incidents in Palo Alto Networks Cortex XDR and Demisto, and updates the incidents properly. When an incident is updated in Demisto, the XDRSyncScript will update the incident in XDR. When an incident is updated in XDR, the XDRSyncScript will update the incident fields in Demisto and rerun the Cortex XDR Blueprint playbook. If you change the name of, or clone the playbook, make sure you update the playbook name in the `Perform Sync` task.
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: ""
      id: 5c69b1e2-0bf3-499a-8079-5be546a741f9
      iscommand: false
      name: ""
      version: -1
    taskid: 5c69b1e2-0bf3-499a-8079-5be546a741f9
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    scriptarguments:
      alert_count: {}
      assigned_user_mail: {}
      assigned_user_pretty_name: {}
      description: {}
      first: {}
      high_severity_alert_count: {}
      host_count: {}
      incident_id:
        simple: ${incident.xdrincidentid}
      interval:
        simple: "5"
      low_severity_alert_count: {}
      manual_severity: {}
      med_severity_alert_count: {}
      notes: {}
      playbook_to_run:
        simple: Cortex XDR Blueprint
      resolve_comment: {}
      severity: {}
      status: {}
      user_count: {}
      verbose: {}
      xdr_alerts: {}
      xdr_file_artifacts: {}
      xdr_incident_from_previous_run: {}
      xdr_incident_markdown_field:
        simple: xdralertstable
      xdr_network_artifacts: {}
      xdr_url: {}
    separatecontext: false
    task:
      brand: ""
      description: Continuously syncs an incident that exists in both Demisto and XDR, by monitoring the incident for modifications, and updates each system accordingly.
      id: dc239475-7348-4926-8504-2751fc9b7650
      iscommand: false
      name: Perform Sync
      script: XDRSyncScript
      type: regular
      version: -1
    taskid: dc239475-7348-4926-8504-2751fc9b7650
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: You can and investigate the incident deeper in XDR
      id: 90afbe07-7f8f-45cc-8ed0-df721932ff6e
      iscommand: false
      name: Manual Task
      type: regular
      version: -1
    taskid: 90afbe07-7f8f-45cc-8ed0-df721932ff6e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    scriptarguments:
      taskID:
        simple: ${XDRSyncScriptTaskID}
    separatecontext: false
    task:
      brand: ""
      description: Stops the scheduled task, specified by the task ID.
      id: 70b87045-b9ed-48ef-8e4f-0d3be2eb60db
      iscommand: false
      name: Stop sync
      script: StopScheduledTask
      type: regular
      version: -1
    taskid: 70b87045-b9ed-48ef-8e4f-0d3be2eb60db
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "8":
    id: "8"
    ignoreworker: false
    note: false
    scriptarguments:
      assigned_user_mail: {}
      assigned_user_pretty_name: {}
      incident_id:
        simple: ${incident.xdrincidentid}
      manual_severity: {}
      resolve_comment: {}
      severity: {}
      status: {}
      unassign_user: {}
    separatecontext: false
    task:
      brand: ""
      description: |-
        Update one or more fields for the specified incident.
        Missing fields are ignored.
        To remove an incident assignment, pass a null value in assignee email argument.
      id: 72e8ab25-a3d5-4214-8e90-cf4a79fe82b6
      iscommand: true
      name: MODIFY THIS TASK - Close XDR incident (choose status)
      script: '|||xdr-update-incident'
      type: regular
      version: -1
    taskid: 72e8ab25-a3d5-4214-8e90-cf4a79fe82b6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 765,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
tests:
  - No test
