name: Delete Defunct Branch Protection Rules
on:
  delete:
    branches:
      - contrib/**

jobs:
  delete_protection_rules_of_deleted_branch:
    runs-on: ubuntu-latest
    if: github.repository == 'avidan-H/content' && github.event.ref_type == 'branch' && startsWith('contrib/', github.event.ref)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Print Context
        run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Create Internal PR
        env:
          CONTENTBOT_GH_ADMIN_TOKEN: ${{ secrets.CONTENTBOT_GH_ADMIN_TOKEN }}
          EVENT_PAYLOAD: ${{ toJson(github.event) }}
        run: |
          echo "Deleting leftover branch protection rule that applied to the contrib branch ${{ github.event.ref }}"
          cd Utils/github_workflow_scripts
          pipenv install --dev
          pipenv run ./delete_bp_rules.py
          echo "Finished Deleting Defunct Branch Protection Rules"
